name: ByteCode CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Java files
      run: ./gradlew --debug --info -stacktrace --warning-mode all --build-cache --scan :ByteCode:GenJavaFiles
      
    - name: Generate javadoc
      run: ./gradlew --debug --info -stacktrace --warning-mode all --build-cache --scan :ByteCode:javadoc
      
    - name: copy javadoc directory
      run: ./gradlew --debug --info -stacktrace --warning-mode all --build-cache --scan :ByteCode:javadocCopy

    - name: Build with Gradle
      run: ./gradlew --debug --info -stacktrace --warning-mode all --build-cache --scan :ByteCode:build

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-generated Java files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: cleaning internal resources
      run: ./gradlew --debug --info -stacktrace --warning-mode all --build-cache --scan :ByteCode:clean